### ISSUE TITLE
Error: Inappropriate authentication

### ISSUE THREAD

**Issue by jonaskellens** [jeremycx/node-LDAP#100]
Hello

trying to perform a lookup, but always getting authentication issue because it seems the ldap-client is not using the given authentication params (binddn & password).

var LDAPSERVER = new LDAP({
    uri: 'ldap://ip.ad.dre.ss',
    connect: function() {
        this.bind({
            binddn: 'cn=A333333,ou=333333,dc=mydomain',
            password: 'supersecret'
        }, function(err) {
            console.log('1.Error = '+err);
        });
    }
}, function(err) {
    getCurrentTime();
    console.log('2.Error = '+err);
    //Search
    var search_options = {
        base: 'dc=333333,dc=mydomain',
        filter: '(&(telephoneNumber=123456789)(sn=*))',
        scope: LDAP.SUBTREE,
        attrs: 'cn',
    };

    LDAPSERVER.search(search_options, function(err, LDAPreturndata){
       if (err) {
          throw new Error('LDAP Search error : '+err);
       } else {
          console.log("LDAP Search result:" + JSON.stringify(LDAPreturndata));
       }
    });
});

On openLDAP-server :

May 23 15:16:35 slap01 slapd[7428]: conn=4099 fd=18 ACCEPT from IP=ip.ad.dre.ss:49658 (IP=0.0.0.0:389)
May 23 15:16:35 slap01 slapd[7428]: conn=4099 op=0 BIND dn="" method=128
May 23 15:16:35 slap01 slapd[7428]: conn=4099 op=0 RESULT tag=97 err=48 text=anonymous bind disallowed

May 23 15:16:35 slap01 slapd[7428]: conn=4099 op=1 SRCH base="dc=333333,dc=mydomain" scope=2 deref=0 filter="(&(telephoneNumber=123456789)(sn=*))"
May 23 15:16:35 slap01 slapd[7428]: conn=4099 op=1 SRCH attr=cn
May 23 15:16:35 slap01 slapd[7428]: conn=4099 op=1 SEARCH RESULT tag=101 err=53 nentries=0 text=authentication required

Script output :

1.Error = LDAPError: Success
2.Error = Error: Inappropriate authentication
filter = (&(telephoneNumber=123456789)(sn=*))
/var/socketio/vcserver.js:227
                                      throw new Error('LDAP Search error : '+err);
                                      ^
Error: LDAP Search error : Error: Server is unwilling to perform
    at Object.<anonymous> (/var/socketio/vcserver.js:227:45)
    at LDAP.dequeue (/var/socketio/node_modules/ldap-client/index.js:225:26)

**Comment by Marangal** [comment]
Hi can you contact me?
